[tool.ruff]
select = ["E", "W", "F", "I", "D", "S", "B", "A", "PT", "Q", "TID"]
ignore = ["B905"]  # only available from python 3.10
line-length = 120

[tool.ruff.per-file-ignores]
"trollsched/tests/*" = ["S101"]

[tool.ruff.pydocstyle]
convention = "google"
